
project_id = "emtwxyywgszhboxpaunk"

[functions.check-vapi-concurrency]
verify_jwt = true

[functions.initiate-vapi-call]
verify_jwt = true

[functions.process-call-queue]
verify_jwt = true

[functions.handle-vapi-webhook]
verify_jwt = false

[functions.create-stripe-checkout]
verify_jwt = false

[functions.create-xaigate-invoice]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
