
project_id = "emtwxyywgszhboxpaunk"

[functions.check-vapi-concurrency]
verify_jwt = true

[functions.initiate-vapi-call]
verify_jwt = true

[functions.create-stripe-checkout]
verify_jwt = true

[functions.check-payment-status]
verify_jwt = true
